# SPDX-FileCopyrightText: 2020 Kerstin Humm <mail@erictapen.name>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "isre1late-server"
version = "0.1.0"
authors = ["Kerstin Humm <kerstin@erictapen.name>"]

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "*", features = [ "ws" ] }
tokio = { version = "*", features = [ "macros", "rt-multi-thread" ] }
reqwest = { version = "*", features = [ "blocking", "json" ] }
diesel = { version = "2.0.0", features = [ "postgres", "postgres_backend", "time" ] }
diesel_migrations = { version = "2.0.0", features = [ "postgres" ] }
serde_derive = "*"
serde = { version = "*", features = [ "derive" ] }
serde_json = "*"
docopt = "*"
log = "*"
time = { version = "*", features = [ "serde-well-known", "local-offset" ] }
urlencoding = "*"
simple_logger = "*"
systemd-journal-logger = "*"
bus_queue = "*"

