# SPDX-FileCopyrightText: 2020 Kerstin Humm <mail@erictapen.name>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "isre1late-server"
version = "0.1.0"
authors = ["Kerstin Humm <kerstin@erictapen.name>"]

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.3", features = [ "json" ] }
reqwest = { version = "*", features = [ "blocking", "json" ] }
rusqlite = { version = "*", features = [ "time" ] }
serde_derive = "*"
serde = { version = "*", features = [ "derive" ] }
docopt = "*"
log = "*"
time = { version = "*", features = [ "serde-well-known" ] }
